version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hyperliquid_postgres
    environment:
      POSTGRES_DB: hyperliquid_db
      POSTGRES_USER: hyperliquid_user
      POSTGRES_PASSWORD: hyperliquid_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hyperliquid_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
