"""Add trader_score column to leaderboard_metrics

Revision ID: 1d71cdb28183
Revises: 
Create Date: 2025-08-10 15:07:54.011538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d71cdb28183'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('leaderboard_metrics', sa.Column('trader_score', sa.Float(), nullable=True, comment='Composite score for ranking traders on the leaderboard'))
    
    # Update existing records with default value
    op.execute("UPDATE leaderboard_metrics SET trader_score = 0.0 WHERE trader_score IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('leaderboard_metrics', 'trader_score', nullable=False)
    
    # Create the index
    op.create_index(op.f('ix_leaderboard_metrics_trader_score'), 'leaderboard_metrics', ['trader_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_metrics_trader_score'), table_name='leaderboard_metrics')
    op.drop_column('leaderboard_metrics', 'trader_score')
    # ### end Alembic commands ###
